domain: fr.pinout.xyz
analytics_id: UA-69846516-3
base_url: /pinout/
resource_url: /resources/
url_suffix:
urls:
  GND: masse
featured:
- 4tronix-picon-zero
- ab-adc-pi-zero
- piborg-ledborg
- pibrella