domain: pinout.xyz
analytics_id: UA-69846516-1
base_url: /pinout/
resource_url: /resources/
url_suffix:
urls:
  GND: ground
featured:
- scorezero
- motozero
- adafruit-arcade-bonnet
- sixfab-xbee-shield